### ISSUE TITLE
yay snippets not working

### ISSUE THREAD

**Issue by Moanrisy** [ianpan870102/.emacs.d#3]
M-x yas-expand not working

type 'src' then press TAB not working too

there is no warning in buffer *Messages*

can you help me setup the yas snippet?

**Comment by ianyepan** [comment]
Hi @mohammadanton I just tried my yasnippet again using the same config here:
```emacs-lisp
(use-package yasnippet
  :diminish yas-minor-mode
  :preface (defvar tmp/company-point nil)
  :config
  (yas-global-mode +1)
  (advice-add 'company-complete-common
              :before
              #'(lambda ()
                  (setq tmp/company-point (point))))
  (advice-add 'company-complete-common
              :after
              #'(lambda ()
                  (when (equal tmp/company-point (point))
                    (yas-expand)))))

(use-package yasnippet-snippets)
```
And it works fine on my machine. (I tried the `main` function snippet in `c++-mode`)
Can you kindly provide me with the major mode you're invoking yas-expand in?

**Comment by ianyepan** [comment]
@mohammadanton Actually, in the latest release I have decided to remove yasnippets, as I think that most users don't use them anyways. However, I'm still more than happy to help your configuration difficulties.
My previous comment above still holds true. Let me know if it works for you.

**Comment by Moanrisy** [comment]
Thanks ian, sorry for the late reply, forget to reply it.

my yasnippet already work after I disable the company mode, turn out it was conflict with yasnippet.
Then I move the keybind for yasnippet from TAB to C-'

Thanks again for this package, I really like the simple config with the org-mode and your opiniated config.

Before I use yours yay-evil, doom is great but there is too much package that I didn't use, although I disable most of them, I feel it still not light dotfiles.

**Comment by ianyepan** [comment]
> Thanks again for this package, I really like the simple config with the org-mode and your opinionated config.

Thank you for the kind words, I'm glad you solved the problem.

> Before I use your yay-evil, doom is great but there is too much package that I didn't use, although I disable most of them, I feel it still not light dotfiles.

Doom is a great 'framework', I have high respect for the developers behind it. However, I also felt that it was too much 'abstraction' and I do like tweaking my config at a lower level. I'm happy my yay-evil project helped you in some way
