### ISSUE TITLE
Config.el 

### ISSUE THREAD

**Issue by Hyjale** [ianpan870102/.emacs.d#6]
Hello,

The `config.el` is not being created in the .emacs.d direcotry as the following error comes up when load up emacs.

`Warning (initialization): An error occurred while loading ‘/home/hyjale/.config/emacs/init.el’:
File is missing: Cannot open load file, No such file or directory, /home/hyjale/.emacs.d/config.el`

Any suggestions?

**Comment by ianyepan** [comment]
Ah, the problem occurs because you're putting your Emacs config directory at `~/.config/emacs/` but yay-evil's `init.el` only specifies a path to `~/.emacs.d/`. (My bad)

Let me quickly fix that!

**Comment by ianyepan** [comment]
Fixed and tested in my latest commit (https://github.com/ianpan870102/yay-evil-emacs/commit/c58f52284ea3263bc74d6f1765041e32ede0d902)

Closing for now, thanks again for pointing this out!
