### ISSUE TITLE
use-pacakge is not a package maneger

### ISSUE THREAD

**Issue by CastixGitHub** [ianpan870102/.emacs.d#7]
I suggest you to change the readme to avoid confusing users :)

**Comment by ianyepan** [comment]
Fair enough, I've received similar feedback before -- time to listen!

**Comment by ianyepan** [comment]
Fixed in https://github.com/ianpan870102/yay-evil-emacs/commit/d1814bc49c070b0fa27b0027675f6f86b08bff37
