### ISSUE TITLE
"startup" and "window" fake packages prevents use of use-package-compute-statistics

### ISSUE THREAD

**Issue by gcoladon** [ianpan870102/.emacs.d#8]
I was interested in speeding up my config.org initialization, so thought to set use-package-compute-statistics to t. When you do that, if you then eval use-package-report, you get a string where one wasn't expected, and that's due to these two sections on lines 49 and 76, which configuring some variables under the auspices of the faux packages "startup" and "window". I propose those settings be put under a real package, or set outside of the (use-package) calls.

I am happy to submit a PR for this that works for me if you'd be open to this change

**Comment by ianyepan** [comment]
Thanks @gcoladon Greg! And sorry for the late reply -- I must have missed your issue.
I will put them under the default "emacs" package. Commit coming.

**Comment by gcoladon** [comment]
LGTM!
